### ISSUE TITLE
onigmo.h appears to be missing

### ISSUE THREAD

**Issue by tolmasky** [subethaedit/SubEthaEdit#104]
I *think* that `onigmo.h` somehow didn't get committed as part of https://github.com/subethaedit/SubEthaEdit/commit/81cfb02f0e45090371307369b813a6b8a58bb60d. I get this error when building: 

```
error: SubEthaEdit/OgreKit/RegularExpression/oniguruma/x86_64/onigmo.h: No such file or directory
```

And the file appears dim in the Xcode project:

<img width="162" alt="Screen Shot 2019-08-07 at 11 20 34 AM" src="https://user-images.githubusercontent.com/23753/62647442-64e1b780-b905-11e9-8746-ef33de8dc8e5.png">

Maybe it is supposed to be an auto-generated file but for whatever reason Xcode isn't generating it. I tried cleaning the build folder too but didn't have any luck with that either.

**Comment by fourplusone** [comment]
Deleting `SubEthaEdit/OgreKit/RegularExpression/oniguruma/x86_64` may resolve this issue

**Comment by tolmasky** [comment]
Yes! Thank you.
