### ISSUE TITLE
New Alert Flow: Scheduled alerts don't show up.

### ISSUE THREAD

**Issue by monkeydom** [subethaedit/SubEthaEdit#106]
E.g. failed re-interpretation of an encoding doesn't show the failed warning to the user anymore.

### Steps:
1) open an untitled document
1) switch encoding to iso latin 1
1) enter an umlaut, e.g. ü
1) switch encoding to utf-8 and choose reinterpret

### Expected Results:
* show the information dialog, thet the reinterpretation failed.

### Results:
* no dialog showing that the reinterpretation failed

I don't know exactly if the previous mechanism was a full queue, but at least this one does not have enough trigger points to call the alert.

**Comment by tolmasky** [comment]
Just want to provide an update that I'm working on this as well as https://github.com/subethaedit/SubEthaEdit/issues/98, but probably won't be able to post PR until the end of the week.

**Comment by monkeydom** [comment]
Thanks for letting me know! Looking forward to your PR.

**Comment by monkeydom** [comment]
Any update on your proposed solution? I'll probably start having a stab on this on my own too, as this functionality is crucial for clean native tab release.

**Comment by monkeydom** [comment]
Okay. The important thing is that this replicates existing behavior. I'd like to keep develop in a state that can be released at a whim, so we can have a release ready on Catalina release date. And this one is the only real blocker currently. So just place a work in progress pr the next time you have some time working on it, so we can finish this up together. I guess this will take some back and forth anyways as the bug is underspeced other than replicating the old behavior, and maybe improve on it where it makes sense.

**Comment by tolmasky** [comment]
OK, I have split my rather large change into smaller chunks, with the first one that specifically addresses this issue ready to go. I'll be writing up my thinking behind it soon and hopefully have thee PR submitted either today or tomorrow.

**Comment by monkeydom** [comment]
In addition to your pull request there is other desired behavior. Don't know how to best sum all up. I guess it is best to have an umbrella bug on the complete sheet behavior now, and small ones describing one specific issue and behavior we need/want.
