### ISSUE TITLE
Get into a weird state where documents no longer open

### ISSUE THREAD

**Issue by tolmasky** [subethaedit/SubEthaEdit#112]
I am not sure how to reproduce this yet, so perhaps it's been fixed with some of the other tabbing changes in the last week, but during my testing, I would occasionally after a good deal of use get into a mode where new documents just wouldn't open (regardless of whether I used the Open Recent menu or dragged a file to the icon, etc.). If this is known to be fixed, feel free to close.

**Comment by monkeydom** [comment]
It might be. There were some nasty retain cycles. (btw: please do paste the Environment part of  Help->Report an issue… so we can track which versions blew up on you)

**Comment by monkeydom** [comment]
Another way of getting there currently is smashing e.g. `cmd-/` in c mode with a long selection. But this seems also to happen on the current release.

**Comment by monkeydom** [comment]
Please comment here again with the Environment part each time you encounter this  again!

**Comment by monkeydom** [comment]
I'll take the lack of new reporting that this isn't reproducible in the most recent and released builds. So I'll close for now. Feel free to reopen if it happens again.
