### ISSUE TITLE
Onigmo is compiled every time.

### ISSUE THREAD

**Issue by fourplusone** [subethaedit/SubEthaEdit#113]
Onigmo is compiled every time resulting in unnecessary long build times

**Comment by monkeydom** [comment]
hmm, that is not what I'm seeing here. Can you specify with a build log? I was looking more on the other end of the spectrum to make sure people don't run into #104 if they don't manually delete the directory.

My oniguruma build phase properly reports:
```
make: Nothing to be done for `install'.
```

But it doesn't clean on clean build folder, which imho it should

**Comment by fourplusone** [comment]
It only happens if the x86_64 folder is newer then `x86_64/libonigmo.la` (I don't know how this happened). Probably the best solution is to place all generated sources & products in `TARGET_BUILD_DIR` as XCode does not seem to call `make clean` anymore. I'll tackle this tomorrow
