### ISSUE TITLE
Highlight tabs in spaces mode, spaces in tab mode.

### ISSUE THREAD

**Issue by tolmasky** [subethaedit/SubEthaEdit#120]
Related to https://github.com/subethaedit/SubEthaEdit/issues/107, it would be nice to "show invisible characters" when those invisible characters aren't expected. So, currently, I can turn on showing invisible characters, but that's seldom what I want (it's too noisy for my taste). *But*, if leading tabs were shown in spaces mode, and leading spaces were shown in tabs mode, then they'd only be shown in a case that is very relevant and possibly the result of a mistake.

**Comment by monkeydom** [comment]
Generally speaking I am all for it. For line endings we already provide this (although in a very intrusive red). 

Generally speaking what should happen is:
a) when setting is on tabs: show leading non-tab whitespace
b) when setting is on spaces: highlight all tabs

Which seems a little bit inconsistent to me, but I do think that is more helpful then just showing all whitespace that is more than one space. It might also need to be a little bit more refined than that to be helpful and not just annoying. Needs another preference too to toggle it on/off. " I would suggest to put in the Editing preferences under view "Show inconsistent whitespace." And the same in the view menu.

All of this is open for discussion and probably worth trying out and iterating around with it.
