### ISSUE TITLE
When multiple files are given to `see`, the first argument doesn't get the right access treatment and is not opened by `SubEthaEdit.app`

### ISSUE THREAD

**Issue by unix-fan** [subethaedit/SubEthaEdit#123]
```
echo a > 1.txt
echo b > 2.txt
see 1.txt 2.txt
```
opens only 2.txt, am i missing something here?

**Comment by monkeydom** [comment]
Opens both for me, maybe you are overlooking a tab for 1.txt? If not more infos for reproduction would be great. E.g. the environment snippet from `Help` ▶ `Report an issue…`

**Comment by unix-fan** [comment]
```
      Model Name: MacBook Pro
      Model Identifier: MacBookPro11,4
      Processor Name: Intel Core i7
      Processor Speed: 2,5 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Memory: 16 GB
      Boot ROM Version: 194.0.0.0.0
      SMC Version (system): 2.29f24
```

**Comment by unix-fan** [comment]
experimented a little bit more, dont make sense ...
```
mkdir somedir
touch somedir/1.txt somedir/2.txt
see somedir/1.txt somedir/2.txt # only 2.txt is opened
see somedir/1.txt # opens 1.txt
see somedir/2.txt # opens 2.txt
see somedir/1.txt somedir/2.txt # opens both 1.txt and 2.txt
???
```

**Comment by monkeydom** [comment]
Indeed. Seeing the same behaviour here. Will investigate. Sounds like a sandbox/security bookmark related issue. Thanks for the additional information!

**Comment by monkeydom** [comment]
Indeed. Somehow the first of multiple arguments does not get the right treatment. (incidentally a workaround for you is to give the first file again to the command line if this is essential for your current workflow)

e.g. this works
```bash
~/tmp$ touch a.txt b.txt c.txt
~/tmp$ see a.txt b.txt c.txt a.txt 
```

**Comment by monkeydom** [comment]
Thanks for finding this one. Was an off by one error based on the fact that applescript is 1-indexed and not 0-indexed, even in the coco api.

You should be able to install and use the attached see tool until the next SubEthaEdit release.
[see-tool.pkg.zip](https://github.com/subethaedit/SubEthaEdit/files/3563679/see-tool.pkg.zip)
