### ISSUE TITLE
Developer certificate of see tool installer expired as of 2019-09-05

### ISSUE THREAD

**Issue by indidev42** [subethaedit/SubEthaEdit#137]
## Short Description

- have just updated to 5.1 from 5.0.2 on my iMac and wanted to reinstall new(est) see
- unfortunately the Apple Developer signature of the certificate did expire 2019-09-05

## Steps to Reproduce the Issue

1. Update from 5.0.2 via Apple AppStore (untested but maybe same for non AppStore version)
2. Have moved SubEthaEdit from /Applications to /Additional-Applications/3rd-Party/...
3. App move to non-standard path properly recognized (thats perfect but shouldn't matter)
4. sudo string copied and pasted to Apple Terminal shell (of admin account with sudo right)
5. executed installation command properly opened the Apple installer but certificate expired
6. workaround to accept installation nevertheless (per user) worked but cert needs update

## Expected Result

Step 5. should just open and install with a valid Apple Developer Installer certificate

## Actual Result

Step 5. executed installation command opened the Apple installer but certificate expired

## Environment

- SubEthaEdit: Version 5.1 (9621)
- System: Version 10.13.6 (Build 17G8030)
- Language: de

```
Hardware:

    Hardware Overview:

      Model Name: iMac
      Model Identifier: iMac11,1
      Processor Name: Intel Core i5
      Processor Speed: 2,66 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 8 MB
      Memory: 8 GB
      Boot ROM Version: 63.0.0.0.0
      SMC Version (system): 1.54f36
      Serial Number (system): W894918Q5PJ
      Hardware UUID: CD1B45A9-3E22-5E82-B754-ECC6FB99509A


```

**Comment by monkeydom** [comment]
Thanks for filing this!
