### ISSUE TITLE
SEE 5.1: Can't Create Tab

### ISSUE THREAD

**Issue by Wingsy** [subethaedit/SubEthaEdit#138]
Prior to 5.1 which I just installed today, I could have 2 open windows then drag one onto the other in the tab region and it would create one window with 2 tabs. Now when I drag one onto the other nothing happens. So how do I start with 2 windows and merge the two into one window with 2 tabs?

**Comment by monkeydom** [comment]
You have two options:
a) turn on always show tab bar in the menu. Then you can drag the single tab the way you wanted to
b) use the merge all windows menu entry to do what you want if you have only two windows open. 

You can also option click the file>open menu emtry to open a file as tab in the active window.

**Comment by Wingsy** [comment]
Thank you. I think that will do it.
-Richard
