### ISSUE TITLE
Reconsider use of PSMTabBarControl

### ISSUE THREAD

**Issue by monkeydom** [subethaedit/SubEthaEdit#14]
With the native tab support of Cocoa it might be worth considering using that instead of the custom PSMTabBarControl solution. However, #1 - Project Context, might still want a custom solution.

**Comment by monkeydom** [comment]
A potential removal is tracked in #43

**Comment by tolmasky** [comment]
I think we can close this with https://github.com/subethaedit/SubEthaEdit/pull/73.

**Comment by tolmasky** [comment]
I think we can close this with #73.
