### ISSUE TITLE
Code unfolding does not work on content that exceeds this visible size of the window

### ISSUE THREAD

**Issue by fourplusone** [subethaedit/SubEthaEdit#143]
## Short Description

Code unfolding does not work on content that exceeds this visible size of the window

## Steps to Reproduce the Issue

1. Create a new document and choose HTML mode
1. Add some content that exceeds the visible size of the window (for example)
 ```html
  <h1>
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	Text
	<foo>
	Bar
	</foo>
</h1>
```
1. Try to fold and unfold a section that is only reachable via scrolling by clicking multiple times on the ribbon

## Expected Result

The section folds and then unfolds again.

## Actual Result

- The section folds but does not unfold
- The folding indicator is initially misplaced 

## Environment

- SubEthaEdit: Version 5.1.2a (9642)
- System: Version 10.14.6 (Build 18G95)
- Language: English

```
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro11,1
      Processor Name: Intel Core i7
```

**Comment by monkeydom** [comment]
I see aspects of this. Note though that a single click already should unfolds. The refresh cycle of the ribbon is definitely out of touch. And sometimes it seems there is clickability but no action. It is probably worth gathering all the cases here to have good fixes.
