### ISSUE TITLE
SubEthaEdit won't open files from Spotlight

### ISSUE THREAD

**Issue by andyvn22** [subethaedit/SubEthaEdit#157]
### Steps
* Spotlight any text file and hit enter

### Results
* SubEthaEdit opens, but does not display the document
* It also doesn't show the document hub, so I guess it knows it was supposed to show a document instead?

### Expected Results
* SubEthaEdit should open and display the opened document, as it does when a file is opened from Finder

### Versions
* SubEthaEdit: 5.1.1
* macOS: 10.14.6

**Comment by andyvn22** [comment]
I don't know what I'm doing, but if it's relevant, SubEthaEdit, Spotlight, and sandboxd each log nothing to Console.app on Spotlight file open attempts, whereas SubEthaEdit logs on Finder double-clicks: `Read options: 0 -- URL: <private> -- purposeID: 2662CFD6-A603-4E02-9EEF-B69B6D8BC9DD -- claimID: D5052CCC-6A9E-4E3A-8D60-EAAF56D0AD21`

**Comment by monkeydom** [comment]
Oh, super interesting. Can reproduce. Thanks for reporting.

**Comment by monkeydom** [comment]
Confirming this is an issue on Catalina, Mojave and High Sierra. Only seems to affect the spotlight return open action though, opening from the quicklook preview from finder works fine.

**Comment by monkeydom** [comment]
@andyvn22 If you could try if https://subethaedit.net/Releases/SubEthaEdit-5.1.2a-9651.zip solves your problem (this is a build of most recent dev with a fix in place, you should be able to just use this instead of the regular download)

**Comment by andyvn22** [comment]
Yup! Spotlight opens files just fine now. Thanks!
