### ISSUE TITLE
Files with hidden extension can't be saved

### ISSUE THREAD

**Issue by andyvn22** [subethaedit/SubEthaEdit#158]
### Steps
* Create a text file
* Get info in Finder and check the "Hide extension" box
* Open in SubEthaEdit

### Results
* The icon in the document titlebar changes to a generic one shortly after opening
* Save attempts complain "The location of the document cannot be determined. You can specify where to save it."

### Expected Results
* The pretty TXT icon should stay in the titlebar forever and saving should work normally

### Versions
* SubEthaEdit: 5.1.1
* macOS: 10.14.6

**Comment by monkeydom** [comment]
Indeed. SubEthaEdit should not be confused by this (albeit confusing) system feature.
