### ISSUE TITLE
bash syntax highlighting issue

### ISSUE THREAD

**Issue by macmisu** [subethaedit/SubEthaEdit#162]
The syntax highlighting for the bash script below not shown properly in SubEthaEdit

```shell-script
#!/usr/bin/env bash
set -e
set -u

sign_csr() {
        local idx=0
        for uri in ${order_authorizations}; do
            authorizations[${idx}]="$(echo "${uri}" | _sed -e 's/\"(.*)".*/\1/')"
            idx=$((idx + 1))
        done
        echo " + Received ${idx} authorizations URLs from the CA"
}
```

Shown in SubEthaEdit:
<img width="556" alt="Screen Shot 2019-11-23 at 9 21 53 PM" src="https://user-images.githubusercontent.com/14041004/69490199-123af580-0e39-11ea-900e-3157f68d7370.png">

**Comment by monkeydom** [comment]
Indeed Thanks for filing this. I would suggest to add String interpolation states for $() for this to work better.
