### ISSUE TITLE
How can I open terminal in enclosing folder?

### ISSUE THREAD

**Issue by Super151804** [subethaedit/SubEthaEdit#165]
I use iTerm2 and I hope open a iTerm2 window

**Comment by fourplusone** [comment]
You can modify the "Open Terminal Here" Script. 

- Download the original script from https://github.com/subethaedit/SubEthaEdit/blob/develop/SubEthaEdit-Mac/Scripts/40-Open%20Terminal%20Here.scpt
- Modify the line `set shellscriptString to "open -a Terminal " & quoted form of realParentPath` to `set shellscriptString to "open -a iTerm " & quoted form of realParentPath`
- Save it to the scripts folder (Scripts Menu > Open Scripts Folder)
- Reload the scripts (Scripts Menu > Reload Scripts)

**Comment by monkeydom** [comment]
Should be resolved by the help of @fourplusone
