### ISSUE TITLE
Style preferences sometimes doesn't take the selected font from the font menu

### ISSUE THREAD

**Issue by monkeydom** [subethaedit/SubEthaEdit#174]
Seems like there is a way where it doesn't participate in the responder chain anymore.

**Comment by hajjimurad** [comment]
I'm experiencing a similar issue.
MacOS Catalina 10.15.7 (19H2)

When the app is restored on restart, it uses some another font. Not sure which, but looks like Times New Roman. 
To fix that I go to Settings -> Styles -> "Apply to Open Documents" and it changes the font for the currently opened Tab, but not for all of them. The rest remain with the wrong font, until I repeat the same steps on them again.
