### ISSUE TITLE
The see-tool installer is signed with an expired certificate

### ISSUE THREAD

**Issue by pierswalter** [subethaedit/SubEthaEdit#179]
## Short Description

The see-tool installer is signed with an expired certificate

## Steps to Reproduce the Issue

1. Install SubEthaEdit 5.1.4 from App Store
2. Call sudo /Applications/SubEthaEdit.app/Contents/SharedSupport/bin/install.command
3. Enter y to continue when asked on the command line

## Expected Result

The Installer app opens without a warning.

## Actual Result

The Installer app opens with the warning that the package has been signed with an expired certificate (Dominik Wagner's Apple developer certificate which has expired on Aug 7, 2020).

## Environment

- SubEthaEdit: Version 5.1.4 (9683)
- System: Version 10.15.7 (Build 19H2)
- Language: de

```
Hardware:

    Hardware Overview:

      Model Name: iMac
      Model Identifier: iMac18,2
      Processor Name: Quad-Core Intel Core i5
      Processor Speed: 3 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Memory: 8 GB
      Boot ROM Version: 428.0.0.0.0
      SMC Version (system): 2.40f1
      Serial Number (system): DGKTVHTNJ1G9
      Hardware UUID: 68ADFD4D-9BCC-59F2-B1FF-E18F6F36D50A

**Comment by monkeydom** [comment]
Thanks for reporting. This is a regular issue and kind of annoying to address without having a completely automated release every year. But will address it in the next release which will probably be after the Big Sur release.
