### ISSUE TITLE
Modernise the Document Hub UI

### ISSUE THREAD

**Issue by jncn** [subethaedit/SubEthaEdit#183]
Since some parts of the SubEthaEdit UI might look a bit out of place on modern macOS, I'd like to work a bit on that.

Here's a quick first mockup for an updated Document Hub. Apart from the new chrome, I tried to vertically align the text labels, removed the gradient backgrounds, and moved the New, Open and Connect buttons to the toolbar.

 Before I start working on it: all feedback welcome. 

<img width="728" alt="Screenshot 2020-12-01 at 01 13 19" src="https://user-images.githubusercontent.com/995815/100680691-69d83f00-3372-11eb-8c19-d3c556b40bef.png">

**Comment by monkeydom** [comment]
Looks like a nice refresh. Thanks for the initiative! Appreciated. I'm wondering if we will go 11 and up only soon, as I don't think maintaining two visual styles is something the project can afford. On top of that the old versions are accessible both in the app store and outside, so I think we are allowed to have more radical requirements if they are warranted.

**Comment by jncn** [comment]
Great! I'll have a look at it in the coming days. 

As for the backwards compatibility, I don't think anything shown here is 11 exclusive. On 10.15 or older, the toolbar would fall back to its old style. I'll provide `xcassets` to replace the SF Symbols in that situation (no code needed).

I'm not that familiar with the current user base, but it's an interesting discussion of course. The current target is set to 10.13, I guess it wouldn't hurt to bring that up to 10.14.
