### ISSUE TITLE
fix or remove azure builds

### ISSUE THREAD

**Issue by monkeydom** [subethaedit/SubEthaEdit#186]
Hey @fourplusone, mind maybe have a look at this? My wisdom there is rusty, and although I probably introduced it with the Apple Silicon additions, I have forgotten most about it again.

**Comment by fourplusone** [comment]
Will do

**Comment by fourplusone** [comment]
With Azure Pipelines being updated to Xcode 12.2 https://github.com/actions/virtual-environments/issues/2056 this issue has been resolved. It seems like building Apple Silicon on Intel hardware was causing the issue.

**Comment by monkeydom** [comment]
Fantastic. Thanks!
