### ISSUE TITLE
[Feature Request] Ability to disable and clear the Find/Replace history

### ISSUE THREAD

**Issue by gothic-bum** [subethaedit/SubEthaEdit#199]
From a privacy perspective, it would be great if there was an option in the preferences user interface to disable and adjust the number of items saved in the Find/Replace history.

This could be similar to the existing option in the preferences user interface which allows the user to set the number of recent documents.

Additionally, it would be helpful if there was some way of clearing the Find/Replace history in the UI (as opposed to having to run a "defaults delete" command from the Terminal).

**Comment by monkeydom** [comment]
Agreed.

Proposed minimal solution: add a clear history entry to the recent searches submenu. Maybe even just put a tickmarked entry there for disabling or adjusting the amount as this doesn't seem like it should be a big preference item or a per mode item.

**Comment by gothic-bum** [comment]
Excellent - thank you!

That's a good idea to place it in the recent searches submenu, which is also consistent with where TextEdit places it.

So perhaps just two menu items are needed, something like:
"Clear Recent Searches" (which is again consistent with TextEdit)
"Remember Recent Searches" (with checkmark to select/indicate if it is enabled/disabled)
