### ISSUE TITLE
Line height

### ISSUE THREAD

**Issue by hmt** [subethaedit/SubEthaEdit#204]
I might be missing it but is there an option to set the line height? I just switched from cotEditor to SubEthaEdit and it feels snappier for me (both editors are great though). i'm missing a feature to set the line height though.

Anecdote, I used to use SEE when it just came out an eternity ago. Nice to have it again.

**Comment by monkeydom** [comment]
Just to be curious: what is the range you would like to change the line height? And in what unit?

**Comment by hmt** [comment]
I have set it to `1.2 times` whatever times it refers to. `em`? So anything between 1 and 1.5 is probably a nice to have and easier on the eye.

I made a screenshot for comparison.

<img width="2184" alt="image" src="https://user-images.githubusercontent.com/1246495/109423957-ea462480-79e1-11eb-8168-86a68ce8d8c7.png">

EDIT: oh dear, it's both Fira Code regular 13.0. It should have been on the screenshot.

**Comment by monkeydom** [comment]
Doing it this way now:
![image](https://user-images.githubusercontent.com/5106/109621842-c26ad400-7b3b-11eb-83b4-e5acff472f56.jpeg)
![image](https://user-images.githubusercontent.com/5106/109622011-eaf2ce00-7b3b-11eb-802a-85eab2be1d7d.jpeg)

**Comment by hmt** [comment]
That looks incredibly beautiful. Nice solution and thank you very much!

**Comment by monkeydom** [comment]
@hmt please do try the pre release version at https://subethaedit.net/Releases/SubEthaEdit-5.2.1-9757.zip if that fulfills your wishes. It might be some time until the final 5.2.1 is released if there aren't any major issues with 5.2

**Comment by hmt** [comment]
It's perfect. Just works as expected. Thank you.
