### ISSUE TITLE
no download

### ISSUE THREAD

**Issue by downhilljoe** [subethaedit/SubEthaEdit#205]
I'm using Mac OS Big Sur. I cannot download an update, I receive the following message:

**The download of the App is not possible

Sub EthaEdit could not be installed, try later again.**

Any Idea what's the reason?

Thanks

**Comment by monkeydom** [comment]
Sadly these are just regular Mac App Store issues we can't do anything about. Log out and back in can help. Restart too. Or worst case deleting the app and redone loading.
