### ISSUE TITLE
How to set ENV PATH on load

### ISSUE THREAD

**Issue by devroute11** [subethaedit/SubEthaEdit#211]
I've been writing scripts natively in SEE however am now writing some scripts that are more portable that I can use with VIM also, these exist in my environment PATH but SEE does not see them.

When I pipe some test text to shell command & "echo $PATH" I get only this:  "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin" which does not include my full path such as ~/bin and /opt/local/bin (ports).  Trying to put a full path in the Pipe Through Shell Command doesn't work either. 

Same happens if I launch SEE from the command line using "see filename.txt"
How can I get SEE to use my full shell PATH?

**Comment by monkeydom** [comment]
the `see` tool does see your whole environment. However, Apps don't. If you want apps to also have environment things set you sadly need to use this invocation on your system:

```
launchctl setenv XDG_CONFIG_HOME "$XDG_CONFIG_HOME"
```

e.g. this would make sure your custom XDG config home is set.

**Comment by devroute11** [comment]
Thanks!  Looks like this works only if you first launch SEE from command line but I can make that work.  Launching the app from dock does not get the PATH.  And if app is already running, even 'see' from CLI doesn't get the PATH.  I can probably just wrap the start around 'see -l'.
