### ISSUE TITLE
Services does not working

### ISSUE THREAD

**Issue by ghost** [subethaedit/SubEthaEdit#214]
## Short Description

Services does not working.

## Steps to Reproduce the Issue

1. Make new "Default" document. And type something.
1. Select All.
1. Select Services>Spotlight in Menubar(or Context Menu).

## Expected Result

Show Spotlight window searching with selected text.

## Actual Result

Nothing happens.
Other service also does not receive selected text.

## Environment

- SubEthaEdit: Version 5.2.1 (9775)
- System: Version 11.5 (Build 20G71)
- Language: English

```
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 8-Core Intel Core i9
      Processor Speed: 2.3 GHz
      Number of Processors: 1
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      System Firmware Version: 1554.140.20.0.0 (iBridge: 18.16.14759.0.1,0)
```

**Comment by monkeydom** [comment]
Indeed. Most Curious why that might be. :(

**Comment by monkeydom** [comment]
A prerelease to test can be found at https://subethaedit.net/Releases/SubEthaEdit-5.2.2-9788.zip

turns out Apple is using deprectaed pasteboard types for this *sadface*
