### ISSUE TITLE
Syntax Checking Broken

### ISSUE THREAD

**Issue by jmunkki** [subethaedit/SubEthaEdit#215]
Using the latest App Store version, trying to check syntax for Python or Lua will result in an relatively obscure error message:

![Screenshot 2021-07-28 at 13 45 47](https://user-images.githubusercontent.com/530260/127309927-af6e46de-d8b7-477e-b53f-76d37272d6b8.png)

"SubEthaEdit got an error: Can’t make 1.40541524954464E+14 into type integer. (-1700)"

I tested this on two Intel-based Macs running Catalina (10.15.7)

## Environment

- SubEthaEdit: Version 5.2.1 (9773)
- System: Version 10.15.7 (Build 19H1217)
- Language: English

```
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro14,3
      Processor Name: Quad-Core Intel Core i7
      Processor Speed: 3.1 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 8 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      Boot ROM Version: 429.120.4.0.0
      SMC Version (system): 2.45f5

**Comment by jmunkki** [comment]
I went back to using a previous version and can use syntax checking normally:

- SubEthaEdit: Version 5.2 (9746)

**Comment by fourplusone** [comment]
I think this was introduced here: https://github.com/subethaedit/SubEthaEdit/commit/8889f140775a322412a0ee1f555afd102786bb78#diff-a096991a084a2128e5accb48de0b000c62834898f3f2c5fc43974b21a7515bc3L6987 as AppleScript cannot handle integers larger than 2^30.
