### ISSUE TITLE
Syntax Validate: SubEthaEdit got an error: Can’t make 1.40596816431152E+14 into type integer. (-1700)

### ISSUE THREAD

**Issue by smckee1** [subethaedit/SubEthaEdit#217]
Hi there,

I am having an issue where the SubEthaEdit validation tools for XML will not work on my machine due to the following error: **SubEthaEdit got an error: Can’t make 1.40596816431152E+14 into type integer. (-1700)**.
<img width="422" alt="Screenshot 2021-09-24 at 12 41 30" src="https://user-images.githubusercontent.com/59446921/134668876-6e21a4f7-b9f8-41cb-a0f2-58da467ad178.png">

I have seen the issue somewhere else but it doesn't seem like it has actually been resolved as I havent had the old versions to roll back to.

I have attached a picture of my current system settings:
<img width="246" alt="Screenshot 2021-09-24 at 12 43 45" src="https://user-images.githubusercontent.com/59446921/134669046-a38a09f9-9150-4a75-9ba3-bbab2d2bcc81.png">

**Comment by monkeydom** [comment]
Hi. This is fixed by #215 in unreleased top of tree. You can download a early build of that here: https://subethaedit.net/Releases/SubEthaEdit-5.2.2-9783.zip
