### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by kossmoboleat** [subethaedit/SubEthaEdit#22]
It would be nice to be able to install SubEthaEdit using [homebrew](https://brew.sh/) from the commandline.

**Comment by monkeydom** [comment]
I don't know how to submit to homebrew casks for apps, but if anyone feels up to it I'm fine with it leaching the https://subethaedit.net/SubEthaEdit.zip which always will turn to the current version and have Sparkle in it for self updates.

**Comment by yanokwa** [comment]
There's a PR at https://github.com/Homebrew/homebrew-cask/pull/55484

**Comment by monkeydom** [comment]
Cool. I would suggest closing this once the pull request is through on the homebrew side.

**Comment by fourplusone** [comment]
I think this issue can be closed ;)
