### ISSUE TITLE
“foo” cannot be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by ndp-opendap** [subethaedit/SubEthaEdit#221]
Files created by or configured to "Open with" SubEthaEdit that reside on an encrypted disk image (created using the Apple DiskUtility) on my new M1 mac (OSX 12.0.1) refuse to open with the following error:
```
“foo” cannot be opened because it is from an unidentified developer.
macOS cannot verify that this app is free from malware.
```
Of course there is a work around by using control-click to open the file but this is getting old really fast. 

_**This only seems to be a problem for files residing on an encrypted disk image. Other files that reside on the system disk open with SubEthaEdit without this problem.**_

If I create the file using SEE on the system disk and configure the file to open with SEE by default that works fine. But if I then copy that file onto the encrypted disk opening it invokes the _unidentified developer_ error.

Has there been any work done to fix this?

It's making me want to abandon SubEthaEdit which I have been using for something like a decade or more.

**Comment by monkeydom** [comment]
Can you give me the concrete example? For regular exectable files we mitigated this in 5.2.2 to not cause the apple quarantine flag when saving file. 

Unfortunately we have no way to mitigate this for newly created files. there you have to do your open stunt at least once or manually remove the quarantine flag using 
```bash
 xattr -d com.apple.quarantine <yourfile>
```

**Comment by ndp-opendap** [comment]
> Can you give me the concrete example? For regular exectable files we mitigated this in 5.2.2 to not cause the apple quarantine flag when saving file.
> 
> Unfortunately we have no way to mitigate this for newly created files. there you have to do your open stunt at least once or manually remove the quarantine flag using
> 
> ```shell
>  xattr -d com.apple.quarantine <yourfile>
> ```

These are not executable files. 

Example:
```
touch foo
see foo # add some stuff to the file
# Use the Finder Command-I to get info and then set the file to open with SEE
cp foo /Volumes/MyEncryptedDiskImage
# Use the finder to navigate to  /Volumes/MyEncryptedDiskImage and try to open foo
```
(I updated the description with additional info just before you posted)

**Comment by ndp-opendap** [comment]
Also I tried this:
```
xattr -d com.apple.quarantine /Volumes/MyEncryptedDiskImage/foo
xattr: /Volumes/MyEncryptedDiskImage/foo: No such xattr: com.apple.quarantine
```
Which makes me wonder: It's an older encrypted disk image. Maybe that is the underlying problem? The older image doesn't have/support newer meta information?

**Comment by ndp-opendap** [comment]
I made a new encrypted disk image on the OSX-12.0.1 system and I was able to get this sorted out. So I think the problem was an Apple issue with older encrypted disk images not supporting the meta attribute  `com.apple.quarantine`

Sorry to trouble you, but your suggestion of using `xattr` led me to the fix.

Thanks!

**Comment by monkeydom** [comment]
Okay, thanks to alerting me to that potential problem and for the resolve.
