### ISSUE TITLE
Extra newline inserted after replacement string

### ISSUE THREAD

**Issue by mc3** [subethaedit/SubEthaEdit#227]
## Short Description

During find/replace, each replacement has an extra newline appended

## Steps to Reproduce the Issue

1. Enter find string "abc"
2. Enter replacement string "xyz"
3. Hit "Replace"

## Expected Result

"abc" replaced by "xyz"

## Actual Result

"abc" replaced by "xyz<LF>"

## Environment

- SubEthaEdit: Version 5.2.4 (9810)
- System: Version 10.15.7 (Build 19H1715)
- Language: de

```
Hardware:

    Hardware Overview:

      Model Name: iMac
      Model Identifier: iMac17,1
      Processor Name: Quad-Core Intel Core i7
      Processor Speed: 4 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 8 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      Boot ROM Version: 170.0.0.0.0
      SMC Version (system): 2.33f12
      Serial Number (system): DGKTCHK5GQ18
      Hardware UUID: 6161C1D2-62CA-5C8C-B1AC-0DF1DBA6B714


```

**Comment by mc3** [comment]
Unreproducible.

**Comment by monkeydom** [comment]
Thanks though. Might be you had a newline in your replace field which can be quite invisible. Maybe we should resort to actually show those characters more clearly, so the intention becomes clear.
