### ISSUE TITLE
Incorrect Mastodon link on FAQ

### ISSUE THREAD

**Issue by sbeitzel** [subethaedit/SubEthaEdit#235]
The [FAQ page](https://subethaedit.net/faq.html) lists `@SubEthaEdit@mastodon.technology` as a source to follow for project updates, but that server seems not to be available.

**Comment by monkeydom** [comment]
Thanks. Yes, sadly the instance was taken down. Also: we didn't use this account much, so we don't have a follow up yet. So removing the references for now.
