### ISSUE TITLE
Safari-style tabs

### ISSUE THREAD

**Issue by tolmasky** [subethaedit/SubEthaEdit#29]
Would you be opposed to me making the tabs in SubEthaEdit match Safari's current style (the ones currently match Safari's old style). Want to make sure that's wanted before spending any time on it.

**Comment by tolmasky** [comment]
I would certainly be in favor of the iterative approach of trying to bootstrap on top of AppKit's now native tabs -- is there anywhere in the documentation that outlines the minimum macOS version that you want to support? That would be my only concern for doing that.

**Comment by monkeydom** [comment]
The current release has a deployment target of 10.11 - but I’m not opposed to raise this quite quickly if its needed or has benefits, now that one more recent compatible version for 10.11 and up is out.

**Comment by tolmasky** [comment]
So just turning on automatic tabbing surprisingly "works", except of course you now get both SubEthaEdit's and AppKit's tabs (nested tabs! that's basically project view right there!). However, there seems to be basically zero documentation for NSWindowTab, etc. so its going to be a fair bit of trial and error.

**Comment by monkeydom** [comment]
It's also slightly faulty (probably because we have overlapping implementations and selectors). Had to disable this "yo dawg" moment pretty close to release as I didn't come across it before. See
6f6eca2c127d3ee0824ade7a985980e409a70977
to probably move back the merge all window selector to the cocoa default one.

**Comment by monkeydom** [comment]
Closing for now with the commit done in #73
