### ISSUE TITLE
Performance Issues While Typing/Scrolling

### ISSUE THREAD

**Issue by tolmasky** [subethaedit/SubEthaEdit#32]
So I am currently using the latest version of SubEthaEdit (5.0 6949) alongside 3.5.4 (which has been my sole editor since it came out basically). I am experiencing significant performance discrepancy while typing in 5.0 vs. 3.5.4. Namely, SubEthaEdit will spin/lock intermittently, and just doing a quick "throw" scroll seems to drop frames and be "janky" as well. The file size are pretty small, about (150 lines or so).I haven't yet gotten the style on both to be identical (I've removed all the bold styles from the theme I'm using, and will be removing all the italics later today in an effort to see if its possibly something related to variable line heights?). But more than anything I wanted to make an umbrella bug to track this and confirm others are seeing it too. If so, happy to start profiling and trying to narrow it down, but wondering if there's some good places to start looking (was there a new syntax highlighting engine introduced in 4, different text rendering engine, etc.)

**Comment by monkeydom** [comment]
In short: Yes. There had been a known performance drop from 3.x to 4.x that never got resolved. So I would applaud you to go in there! I haven’t had time to do so myself. I found a pretty blatant one on PSMTabBarControl that was just redrawing constantly before the release of 5 but could not divert more time to it.

Thanks in advance!

**Comment by monkeydom** [comment]
Please verify against 5.0.2 - this sounds a lot like #60 which was fixed in that release

**Comment by tolmasky** [comment]
I feel like I used to have the problem with one window, but trying it now, it does seem quicker. I'll try using it for a couple days and report back. I'll close it if it feels like this fixed it.

**Comment by tolmasky** [comment]
I have used it for a while now, and while I think 3.5.4 is still a little faster, the obvious pauses are now gone. I think we can go ahead and close this. Thanks to @kluepfel for the reproduction and @monkeydom for fixing it!
