### ISSUE TITLE
Old website on "codingmonkeys.de/subethaedit/old" should be removed

### ISSUE THREAD

**Issue by docnop** [subethaedit/SubEthaEdit#42]
When using google to find a C# mode for SubEthaEdit (search term "subethaedit c#"), the first suggestion for me is https://www.codingmonkeys.de/subethaedit/old/modes.html.
It wasn't obvious for me at first, that this was an obsolete site with links to obsolete modes that do no longer work with a current version of SubEthaEdit.
I'd like to suggest the "old" website to be removed to avoid confusion for others.

**Comment by Hipska** [comment]
I came to this issue while searching for new modes, as SEE has very little modes by default. What/where is the current place to find modes?

I'm looking for YAML at least.

**Comment by monkeydom** [comment]
Not app supplied modes go to https://github.com/subethaedit/SubEthaEdit-Modes/tree/master/Modes - however the policy now would be to integrate modes quite quickly into the main distribution. There hasn't been an influx of new modes / ported good old modes though, so this is a major area for potential contributions.

**Comment by monkeydom** [comment]
Closed as now all old website references forward to SubEthaEdit.net to not be confusing.
