### ISSUE TITLE
Text is (annoyingly and repeatedly) moved under the line number bar when wrap lines is off

### ISSUE THREAD

**Issue by ferben** [subethaedit/SubEthaEdit#46]
## Short Description
Code folding bar overlay over text repeatedly

## Steps to Reproduce the Issue

1. Open BASH file (UTF-8/LF) - my example is 1000 lines, 3 spaces indentation, approx 5 indentation in file max.
2. Show Code folding & line numbers bar
3. Scroll up & down repeatedly

## Expected Result
Text have to be visible from begginig of lines

## Actual Result
Code folding bar overlay over first 5 or 6 characters after up/down scrolling action

## Environment

- SubEthaEdit: Version 5.0 (6949)
- System: Version 10.14.2 (Build 18C54)
- Language: English

```
Hardware:

    Hardware Overview:

      Model Name: iMac
      Model Identifier: iMac17,1
      Processor Name: Intel Core i5
      Processor Speed: 3,2 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Memory: 16 GB
      Boot ROM Version: 161.0.0.0.0
      SMC Version (system): 2.33f10
      Serial Number (system): DGKRG05CGG7V
      Hardware UUID: 17421B1D-980D-5BA2-9560-74EA62462E44


```

**Comment by ferben** [comment]
## Additional info
I found out that this bug appear only if you **uncheck** "Wrap Lines" option in AppPreferences->Editing

**Comment by kluepfel** [comment]
I can confirm the issue occurs when
* Wrap Lines is off
* Show line numbers and folding bar
* Text is wider (horiz) and longer (vert) than the window.

The issue can be triggered by pressing page up/dn
