### ISSUE TITLE
Lower versions of macOSX?

### ISSUE THREAD

**Issue by yeager2002** [subethaedit/SubEthaEdit#47]
HI
Is it possble to compile SubEthaEdit for lower version macOSX for example 10.9 or 10.10?
Thanx.

**Comment by tolmasky** [comment]
I'm not sure about getting the latest to build for that (especially considering we are actively discussing changes that would make the version of macOS even more restrictive). However, I believe you can revert SubEthaEdit to one of the earlier tags (e.g. [3.5.4](https://github.com/subethaedit/SubEthaEdit/tree/SubEthaEdit-Mac-3.5.4) ) which may compile on earlier versions.

**Comment by monkeydom** [comment]
The current cleaned up code base is 10.11 and above only. However, I would not oppose someone dig out old developer tools and build e.g. a 4.x or 3.5.4 version without licence keys if so desired. In fact a 3.5.4 binary still is alive at https://subethaedit.net/downloads/SubEthaEdit-354.zip

I probably should go ahead and post a license code here too.
