### ISSUE TITLE
Integration with Fetch broken

### ISSUE THREAD

**Issue by iJoost** [subethaedit/SubEthaEdit#52]
When I open a file directly from Fetch into SubEthaEdit the file will open and I can edit it. But when I save the changes they do not get send back to the original file on the FTP server. This used to work just fine with previous versions of SubEthaEdit (I just upgraded from the 32 bit version to version 5.0)

**Comment by monkeydom** [comment]
In the meantime I can recommend Cyberduck which it works with. Will try to see why fetch broke…

**Comment by monkeydom** [comment]
Preliminary investigation shows 2 problems:
a) the odb parameters send on open aren't parsed anymore because of timing changes in the framework (e.g. the arriving apple event is not current anymore at the point we look into it). This is fixable, however
b) the necessary event that is sent does not arrive at fetch due to sandboxing. I'm not sure there is a way around it

I'm in contact with FetchSoftWorks to see if there is a good solution around this.

**Comment by iJoost** [comment]
I appreciate anything you can do towards restoring interoperability between the two. :-) Don't know what SEE is. But I'm using Fetch mostly for a limited number of webservers, so perhaps usefulness would be "enough".

Anyway, you did say it works with Cyberduck, so if all else fails I do have a workaround.

**Comment by monkeydom** [comment]
This will probably need a fetch update to remove SubEthaEdit from their list of supported editors for the ODB protocol to work. In the meantime you can get SubEthaEdit to work with fetch, by disabling this protocol for all apps by putting this in the terminal:
`defaults write com.fetchsoftworks.Fetch UseExternalEditorProtocol -bool false`

**Comment by monkeydom** [comment]
> I appreciate anything you can do towards restoring interoperability between the two. :-) Don't know what SEE is. But I'm using Fetch mostly for a limited number of webservers, so perhaps usefulness would be "enough".
> 
> Anyway, you did say it works with Cyberduck, so if all else fails I do have a workaround.

If you contact me via subethaedit-bugs@lone.monkey.productions I can send you a work in progress version to test out if that fixes the problem for you.

**Comment by iJoost** [comment]
Works!!! :-)
