### ISSUE TITLE
Feature Request:  Overwrite mode

### ISSUE THREAD

**Issue by d-a-v-i-d-j** [subethaedit/SubEthaEdit#58]
It seems that the ability to overwrite text in a text editor is as rare as purple unicorns.  After a quick survey of Mac editors (BBedit, Text Wrangler, Word, Pages, Xcode, etc) none of them seem to have this ability.  I have an emacs editor that does, but I hate emacs.  I also had a vim editor (which I love[d]), but it's been flakey for the last few years, and I've given up on it.

I could hop into a terminal and just use vi, but I would prefer the conveniences of sticking with a more visual editor.

Anyway, I hope you consider adding this seemingly simple, yet nigh impossible to find, feature.

**Comment by monkeydom** [comment]
Overwrite would be a step towards a more modal, vi like interface and away from the system standard text behaviour. I'm sorry to say that this is not something SubEthaEdit is heading towards.
