### ISSUE TITLE
Bash mode Re-Indent issue

### ISSUE THREAD

**Issue by iFredOS** [subethaedit/SubEthaEdit#62]
## Short Description
If we use a "else" in a Bash script, the re-indentation don't understand and shift right the else instead of following the "if" statement.

## Steps to Reproduce the Issue

1. Create a Bash script with a if/else
2. Select All text
3. Menu: Format -> Re-Indent

## Expected Result
```bash
if [ "a" != "b" ]; then
	echo "true"
else 
	echo "false"
fi
```
## Actual Result
```bash
if [ "a" != "b" ]; then
	echo "true"
	else 
	echo "false"
fi
```
## Environment

- SubEthaEdit: Version 5.0.1 (9520)
- System: Version 10.14.3 (Build 18D109)
- Language: English

```
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro10,1
      Processor Name: Intel Core i7
      Processor Speed: 2,6 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Memory: 8 GB
      Boot ROM Version: 251.0.0.0.0
      SMC Version (system): 2.3f36
      Serial Number (system): C02JN3U8DKQ5
      Hardware UUID: 4A39AF10-69D0-5604-9BC4-D26793268E6E


```

**Comment by ferben** [comment]
Confirmed.
After reformat "else" si not on the left ⇒ see screenshot.
![screenshot](https://user-images.githubusercontent.com/45659268/55661794-5deb5100-580e-11e9-8dd1-e6a12937c307.png)

**Comment by monkeydom** [comment]
I do think there is some precedence how to do this in the ruby mode. It does involve some weird stunts to place the begin and ends of states though.
