### ISSUE TITLE
Inserting unsupported text is always placed at the beginning of the document.

### ISSUE THREAD

**Issue by tolmasky** [subethaedit/SubEthaEdit#85]
I ran into this bug while converting thee deprecated methods, and I have a fix on hat branch, but want to note it here to track it.

Steps to reproduce:

1. Create a new document.
2. Set file encoding to Western ASCII
3. Type some supported text.
4. *Type* (don't paste) a character that can't be supported in ASCII.
5. You will get the dialog, choose insert.
6. The character will be placed at the beginning of the document.

**Comment by monkeydom** [comment]
Interesting. Nice find.
