### ISSUE TITLE
Native Tabs: "file has been modified by another application" appears immediately

### ISSUE THREAD

**Issue by fourplusone** [subethaedit/SubEthaEdit#98]
## Short Description

The sheet "The document's file has been modified by another application. Do you want to revert the document?" appears immediately and dissapears after the animation has finished if a file has been edited outside of SEE 

## Steps to Reproduce the Issue

1. Open a file
1. Press cmd+T to open another tab
1. Open the same file in another editor
1. Edit & Save the file in another editor
1. Focus SubEthaEdit

## Expected Result

The sheet "The document's file has been modified by another application. Do you want to revert the document?" appears once you switch to the tab with the affected file

## Actual Result

The sheet "The document's file has been modified by another application. Do you want to revert the document?" appears immediately and dissapears after the animation has finished 

## Environment

- SubEthaEdit: Version 5.1.0a (9567+)
- System: Version 10.14.5 (Build 18F132)
- Language: en

```
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro11,1
      Processor Name: Intel Core i7
      Processor Speed: 3 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 4 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      Boot ROM Version: 153.0.0.0.0
      SMC Version (system): 2.16f68
      Serial Number (system): [redacted]
      Hardware UUID: [redacted]

```

**Comment by monkeydom** [comment]
We don't want the current behavior. That is for sure.

I do think the previous behavior was less introsive, but have to test. E.g. in the previous behavior the sheet was imho only shown when you switched to the document. this way multiple changes could easily coalesce. I think I would like that back.

So: only show sheet when switching to a document. Maybe put a accessory view in the tab to show that there is an issue. I do think we had the warnings sign pre native tabs.

**Comment by monkeydom** [comment]
Yes, I do think we need the old behavior back. E.g. show the sheet only after the user actively switched to the tab, and show a warning in the tab icon.

![Pasted_Image_07_08_19__20_10](https://user-images.githubusercontent.com/5106/62646873-8cf60880-b94f-11e9-96df-09838e6eef84.jpg)

**Comment by monkeydom** [comment]
Probably also related to #86 as the mechanism that displays the warnings changed too.

**Comment by monkeydom** [comment]
There is also the problem that regular scheduled alerts don't show up. Easy repro steps:
* open an untitled document
* switch encoding to iso latin 1
* enter an umlaut, e.g. ü
* switch encoding to utf-8 and choose reinterpret

### Expected Results:
* show the information dialog, thet the reinterpretation failed.

### Results:
* no dialog showing that the reinterpretation failed

I don't know exactly if the previous mechanism was a full queue, but at least this one does not have enough trigger points to call the alert.

**Comment by monkeydom** [comment]
I added a caution symbol to be used in 686667b6745f454d4eace398f8f470461498bc91 so the art is prepared.
